### ISSUE TITLE
Add an option to adjust or disable all keyboard shortcuts or reassign them.

### ISSUE THREAD

**Issue by nabileisa** [willmiao/ComfyUI-Lora-Manager#251]
**Is your feature request related to a problem? Please describe.**
In vivaldi browser and im sure in others as well, This extension's keyboard shortcuts override the default browser ones, like to select all text in an input `ctrl+a` and `ctrl+f` to search in page , I want to disable or reassign them.

**Describe the solution you'd like**
add a toggle to disable all shortcuts or a fine grained option to reassign or disable each one.

Thanks

**Comment by willmiao** [comment]
Thanks for the valuable feedback! I’ve already refined the custom Ctrl+A shortcut so it won’t trigger when a search input is focused — you should now be able to use Ctrl+A to select all text inside inputs as expected. As for the Ctrl+F shortcut, I’ll fix that as well once I figure out the best approach.

Appreciate you pointing this out!

**Comment by nabileisa** [comment]
Thanks for the quick reply and you awesome work on this manager , I use it all the time and it has been a great help in keeping all my loras and their trigger words organized.
Regarding `Ctrl+A` : Aside from not triggering when a text input is focused I would prefer if possible that it would only be enabled only if `Bulk` mode is active , That way it would more intentional and guarantee it will not interfere with any thing else in the future.

**Comment by WooHyun66** [comment]
I don't know if anyone has encountered the same problem with me, every time I accidentally press ctrl+z to undo a certain movement in the workflow run, lora manager will automatically restore the settings, resulting in the image that has already been generated and is being edited can only be re-generated, can you turn off lora node on the undo function of the corresponding?

**Comment by willmiao** [comment]
> I don't know if anyone has encountered the same problem with me, every time I accidentally press ctrl+z to undo a certain movement in the workflow run, lora manager will automatically restore the settings, resulting in the image that has already been generated and is being edited can only be re-generated, can you turn off lora node on the undo function of the corresponding?

This issue isn’t caused by LoRA Manager hijacking the Ctrl+Z shortcut. Based on your description, it’s likely a compatibility issue caused by the `ComfyUI_Custom_Nodes_AlekPet` custom node (based on what you described I guess you have it installed). This problem was addressed in version 0.8.19, so try updating to that version — the issue should be resolved.

**Comment by WooHyun66** [comment]
> > I don't know if anyone has encountered the same problem with me, every time I accidentally press ctrl+z to undo a certain movement in the workflow run, lora manager will automatically restore the settings, resulting in the image that has already been generated and is being edited can only be re-generated, can you turn off lora node on the undo function of the corresponding?不知道有没有人遇到过和我一样的问题，每次我在 workflow run 中不小心按 ctrl+z 撤消某个动作时，lora manager 就会自动恢复设置，导致已经生成正在编辑的图像只能重新生成，请问可以关闭 lora node 上对应的 undo 功能吗？
> 
> This issue isn’t caused by LoRA Manager hijacking the Ctrl+Z shortcut. Based on your description, it’s likely a compatibility issue caused by the `ComfyUI_Custom_Nodes_AlekPet` custom node (based on what you described I guess you have it installed). This problem was addressed in version 0.8.19, so try updating to that version — the issue should be resolved.这个问题并非由 LoRA Manager 劫持 Ctrl+Z 快捷键引起的。根据您的描述，这可能是由 `ComfyUI_Custom_Nodes_AlekPet` 自定义节点引起的兼容性问题（根据您描述，我猜测您已经安装了该节点）。此问题已在 0.8.19 版本中得到解决，请尝试更新到该版本 - 问题应该会得到解决。
Thank you for your guidance, I'll try it now

**Comment by WooHyun66** [comment]
> > I don't know if anyone has encountered the same problem with me, every time I accidentally press ctrl+z to undo a certain movement in the workflow run, lora manager will automatically restore the settings, resulting in the image that has already been generated and is being edited can only be re-generated, can you turn off lora node on the undo function of the corresponding?不知道有没有人遇到过和我一样的问题，每次我在 workflow run 中不小心按 ctrl+z 撤消某个动作时，lora manager 就会自动恢复设置，导致已经生成正在编辑的图像只能重新生成，请问可以关闭 lora node 上对应的 undo 功能吗？
> 
> This issue isn’t caused by LoRA Manager hijacking the Ctrl+Z shortcut. Based on your description, it’s likely a compatibility issue caused by the `ComfyUI_Custom_Nodes_AlekPet` custom node (based on what you described I guess you have it installed). This problem was addressed in version 0.8.19, so try updating to that version — the issue should be resolved.这个问题并非由 LoRA Manager 劫持 Ctrl+Z 快捷键引起的。根据您的描述，这可能是由 `ComfyUI_Custom_Nodes_AlekPet` 自定义节点引起的兼容性问题（根据您描述，我猜测您已经安装了该节点）。此问题已在 0.8.19 版本中得到解决，请尝试更新到该版本 - 问题应该会得到解决。

I just tried it, and even after removing the AlekPet node and updating the lora node to the latest version, I still have this problem.As soon as ctrl+z is pressed, the lora settings are reverted (e.g. clip strength set to 0.2 goes back to 1).I've given up on this, as long as I don't press ctrl+z.

**Comment by willmiao** [comment]
@WooHyun66 先确认已经升级到0.8.19版本，你可以通过ComfyUI设置中的About进行查看。如图：

<img width="667" height="163" alt="Image" src="https://github.com/user-attachments/assets/68fb95b8-f80d-46d9-bf90-407ca13020f3" />

然后刷新ComfyUI页面（F5或Ctrl+F5），以确保加载最新前端代码。

**Comment by WooHyun66** [comment]
> [@WooHyun66](https://github.com/WooHyun66) 先确认已经升级到0.8.19版本，你可以通过ComfyUI设置中的About进行查看。如图：
> 
> <img alt="Image" width="667" height="163" src="https://private-user-images.githubusercontent.com/11958890/464644536-68fb95b8-f80d-46d9-bf90-407ca13020f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxNDg2NTQsIm5iZiI6MTc1MjE0ODM1NCwicGF0aCI6Ii8xMTk1ODg5MC80NjQ2NDQ1MzYtNjhmYjk1YjgtZjgwZC00NmQ5LWJmOTAtNDA3Y2ExMzAyMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEwVDExNTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMjQwODJiZjM0MDNhMDdkNmYyNWMyOWU3MDdjMzhjMzA4Y2M5ZjYxYjQzNGRhZGJmZDExY2U1NTg1YmMwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Ywra8WkaI0pOZT2Q6Hcage0_0j3Jt8J4qZ07ISiV2Y">
> 然后刷新ComfyUI页面（F5或Ctrl+F5），以确保加载最新前端代码。

<img width="1081" height="141" alt="Image" src="https://github.com/user-attachments/assets/c9e87f3e-834f-454f-839e-f0d7c301db69" />
Ha ha, but it's still the same.
