### ISSUE TITLE
[FR] Separate Lora Manager Install/Settings?

### ISSUE THREAD

**Issue by Caio-Branco** [willmiao/ComfyUI-Lora-Manager#623]
I recently did a clean install of ComfyUI and kept the old install for testing of new nodes and NSFW and I thought I could have separate lora manager instances for each of them but apparently I can't they all default to what's in the settings, I don't even know how the newly installed lora manager got the configs from the old lora manager.

Maybe its possible and I'm missing something but it would be great if there was a way to have separate instances of lora manager localized to the comfyui where they are currently installed, making it truly portable. Or at least different profiles for the settings which would include the folders where its working with?

Edit: I see the settings.json.example from the instructions on a standalone install, but if I edit that on one of my comfyUI installs would that be the equivalent of localizing the folder settings to that instance of comfyUI?

Edit 2: I see in the folder settings there is an Active Library setting but I only have on ComfyUI entry which I then can select one of the folder of the current Comfy install I'm running and default, which I can't figure how to pick a folder for that, I also tried to edit setting.json but it doesn't seem to relate to this.
Is this Active Library the solution to what I'm trying to do? Although it still wouldn't separate the Examples Download folder which I would also like to have separated and other settings too.

<img width="679" height="465" alt="Image" src="https://github.com/user-attachments/assets/039bc88c-11cc-4767-aa20-3e5e88560795" />

Anyway, thanks for this amazing work.

**Comment by willmiao** [comment]
The reason the new LM picked up your old configs is because the settings.json file has been relocated to the user config folder to prevent accidental deletion.

And yes — the Active Library option is indeed the solution for what you’re trying to do. It’s an experimental feature that lets you manage multiple libraries under a single LM instance and switch between them at runtime.

However, for setups like yours with two separate ComfyUI instances, this feature still needs some adjustments.

So for now, I’ve just pushed a fix that lets you choose whether to use the settings.json inside the repo folder (like before) instead of the shared one in the user config directory. Please update to the latest version, then copy settings.json.example as settings.json in your new ComfyUI setup, configure it as usual, and set `"use_portable_settings": true`.

**Comment by Caio-Branco** [comment]
Hey thanks for the reply, I just updated it and setup the json files, I have one json file in each installation pointing to its own subfolders and when I open that install it still shows the last opened one loras, and at first I was having to go on settings and select the folders in the drop down menus (which would just show subfolders for that install) and then refresh, then I figured if I leave the fields under Active Library blank and refresh it will get the appropriate loras for that install, but only after a refresh.
Either way was under the Active Library "ComfyUI" I haven't figured what "Default" does. Is that how it's supposed to work by leaving the fields blank?
I assume its the same for the CivitAI API key? Should I leave it blank and it will get the API key from the json file?

I know this is something you are working on but it's not the ideal solution yet, It would also be ideal for the Download Examples folder to be different for each comfyui install too. To be honest ideally everything would be unique to its install just like comfyui portable is completely isolated within each install, so one can experiment and have different environments safely self contained and portable, but I'm not a developer so i don't know what that would entail for your plugin, maybe you could have a portable version or maybe that could be a switch, or maybe having it be an overall profile inside the application like you are doing right now is the only thing possible while keeping the convenience of the app, I don't know, but there are many other things I would like to be totally separated between installs.

Like right now If I want to move my comfyUI install between computers I know exactly what would happen and what would I need to copy, but now your plugin wouldn't be the same way because apparently there are config files being saved in a user directory which I don't know how I would go about transferring correctly or backing it up.
 
Just my two cents and again thanks for all the work, let me know if I got something wrong, I've read the documentation and watched the videos but it doesn't seem to cover these issues.

Edit: I just noticed that leaving the folder fields blank creates a problem downloading loras with the browser extension, they go somewhere I couldn't find and they dont show up in the manager even thou the extension says they have been downloaded, its fixed by selecting the lora subfolder.

**Comment by willmiao** [comment]
Sorry, I’m away from home until tomorrow, but I’ll check it out once I’m back.

**Comment by willmiao** [comment]
Please update and give it another try. As long as you set `"use_portable_settings": true` in the `settings.json` file under the repo folder, LM will now use that file instead of the one in the user config folder, making this LM instance fully portable.

**Comment by Caio-Branco** [comment]
Ok I updated it. What works: Both installs have their settings.json, I open one install, open the LM UI and the active library is set to ComfyUI and the subfolder fields are empty, I Refresh Model List in the UI and it shows the correct loras. Close this install, close the LM UI open the other install, open LM UI it still shows all the same loras, click Refresh Model List, it displays the correct loras, every other setting is still shared.

If possible could you make it refresh the model list? I understand if I keep the UI open it wouldn't make sense to keep checking, but if I close it and open it again from the other install I don't want to see the previous loras, so it could be on opening the UI or if you refresh the whole page it updates to the correct loras.
Also if you could separate the download example folders. It would be fine to set the path to different example folders according to the install but a different approach could be to have the option to just have LM make the folder next to comfyui as I tried to do for each install like in the screenshot so I could move it somewhere else and its all self contained.

Here is my use case, I stream and one install has inappropriate loras for TOS with their thumbnails or just junk and test loras and the other install is the cleaned up ones I use on stream. So I understand If I leave the LM UI open as I change comfy instances it would be hard to make it change itself without it "asking" all the time which instance is open, but If it could refresh that when I open the LM UI fresh from comfy, or on refresh page, it would be better than having to rely on the refresh model list.

And again, maybe I'm missing something but it's not fully portable, they share most settings including the examples folder which I just tested. 

Thanks for replying and working to improve it, I'm sure most people would appreciate a fully contained portable installation that they can take with their comfyui portable and control the contents of each.

<img width="716" height="228" alt="Image" src="https://github.com/user-attachments/assets/35c2a36a-d37c-4741-9dbd-2590d4456f71" />

**Comment by willmiao** [comment]
I’ve tested this locally using two separate ComfyUI installations, each with its own LoRA Manager instance inside their respective custom_nodes folders. The current implementation is already fully portable and self-contained.

Please make sure of the following:

1. Update to the latest nightly build.

2. Copy settings.json.example to settings.json, and set "use_portable_settings": true.

3. If LoRA Manager starts together with ComfyUI, **don’t** manually set folder_paths; those values will be automatically retrieved from the ComfyUI API.

4. You don’t need to worry about Active Library in your setup — when LM is launched by ComfyUI, there will only be one library (comfyui), so multiple-library logic doesn’t apply in your case for now.

5. To verify which settings file is being used, open Settings → click the link icon in the header area. This will open the folder containing the active settings.json, so you can confirm the exact path and review its content.

6. If needed, click “Rebuild Cache” from the Refresh button dropdown to rescan all model metadata files.

**Comment by Caio-Branco** [comment]
Thanks for the reply, sorry if I was long winded was trying to give as much info as possible.
So I think I understand now, and seeing the settings file in the AppData folder it looks much more as what I was imagining, so I will be testing more and if needed I will delete everything and start over I just need to clarify a few things:
1. In the screenshot bellow is what I was doing so far, having the settings.json file in the main folder, It's the first time I see the settings file in the AppData folder and the end of it looks like the example file, does that mean I should modify the file in AppData accordingly, or have a file stay in the node folder like the screenshot?
2.  In your point 3, does that mean I should delete the folder paths and leave it blank under "loras", "checkpoints" and "embeddings"?
3. The settings file in AppData has use_portable_settings as false while the one I had in the node folder was true, so I think I was really missing something, my question is having multiple settings would mean each node folder gets its own complete settings file, or multiple settings files are created in AppData?

Edit: So just to clarify, the whole time I was just making a copy of settings.json.example next to it called settings.json and modifying what looks like just an excerpt from the whole setting file, I didn't knew about the settings file in AppData this whole time, so it seems that when you were telling me to copy the info from the example file I was supposed to copy that to the full file in AppData, is that correct?

Sorry for the confusion, but I think I'm getting it now I was just missing something.

<img width="969" height="733" alt="Image" src="https://github.com/user-attachments/assets/dcc9b72d-aed6-4253-a7d6-c8f6bf090280" />

**Comment by willmiao** [comment]
Hey, sorry for the confusion — I probably didn’t explain it clearly enough.
If you’re running LoRA Manager with **ComfyUI (not standalone)**, here’s what to do:

1. In `ComfyUI/custom_nodes/ComfyUI-Lora-Manager`, delete any existing `settings.json` and `model_cache` folder.

2. Copy `settings.json.example` → `settings.json` in current folder, set `"use_portable_settings": true`, and save. No other edits needed.

3. Start ComfyUI — LoRA Manager will automatically load models for this instance.

4. Repeat the same for other ComfyUI instances you have.

Notes:

- When running inside ComfyUI, **don’t set** `folder_paths` — that’s only for standalone mode.

- You’ll only need to edit `settings.json` once; other options (like API key) can be set through the Settings UI.

**Comment by Caio-Branco** [comment]
Hey sorry for the delay, It worked now finally!
So the problem for me was that the settings file and the model_cache folder in AppData existed, once I deleted those it read the local settings.json in the custom nodes folder and it worked as intended.
Thanks for the patience and I hope this helps you deal with this case when people previously had a non portable install.

**Comment by willmiao** [comment]
Appreciate the follow-up! I tested that setup too — I’ve got one ComfyUI using the user config folder and another running full portable.

It probably just happened to work right after you cleared the user config folder, but in theory it should’ve worked either way.
